In [57]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

In [58]:
digits = load_digits()

In [59]:
df = pd.DataFrame(digits.data,columns=digits.feature_names)
df['target'] = digits.target
df

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0,9
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0,0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0,8
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0,9
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0,8

In [60]:
x_axis = df.drop(['target'],axis='columns')
x_axis

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

In [61]:
y_axis = digits.target
y_axis

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

## Approach 1: Use train test split and manually tune parameters by trial and error

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_axis,y_axis,test_size=0.2,random_state=42)

In [63]:
svm = SVC(kernel='rbf',C=10,gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.5222222222222223

In [64]:
svm1 = SVC(kernel='linear',C=10,gamma='auto')
svm1.fit(X_train,y_train)
svm1.score(X_test,y_test)

0.9777777777777777

## Approach 2 : use k fold validation

In [65]:
from sklearn.model_selection import cross_val_score

In [66]:
cross_val_score(LogisticRegression(),x_axis,y_axis,cv =5)

d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [67]:
cross_val_score(DecisionTreeClassifier(max_depth=5,random_state=42),x_axis,y_axis,cv=5)

array([0.61944444, 0.49166667, 0.67688022, 0.73537604, 0.62395543])

In [68]:
cross_val_score(RandomForestClassifier(n_estimators=10),x_axis,y_axis,cv=5)

array([0.925     , 0.88055556, 0.92200557, 0.94707521, 0.88300836])

In [69]:
cross_val_score(SVC(gamma='auto',kernel='rbf',C=50),x_axis,y_axis,cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [70]:
cross_val_score(GaussianNB(),x_axis,y_axis,cv=5)

array([0.78055556, 0.78333333, 0.79387187, 0.8718663 , 0.80501393])

In [71]:
cross_val_score(MultinomialNB(),x_axis,y_axis,cv=5)

array([0.88611111, 0.83611111, 0.8551532 , 0.94150418, 0.83286908])

## Above approach is very manual. We can use for loop as an alternative

In [72]:
kernel = ['rbf' , 'linear']
c = [1,10,20,50]
avg_score = {}
for kval in kernel:
    for cval in c:
        cv_score = cross_val_score(SVC(kernel=kval,C=cval,gamma='auto'),digits.data,digits.target,cv=5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_score)

avg_score

{'rbf_1': np.float64(0.448545341999381),
 'rbf_10': np.float64(0.47636645001547506),
 'rbf_20': np.float64(0.47636645001547506),
 'rbf_50': np.float64(0.47636645001547506),
 'linear_1': np.float64(0.9476973073351903),
 'linear_10': np.float64(0.9476973073351903),
 'linear_20': np.float64(0.9476973073351903),
 'linear_50': np.float64(0.9476973073351903)}

## Approach 3 : Use grid search cv

In [75]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma='auto'),{
    'C' : [1,10,20,50],
    'kernel' : ['linear','rbf']
},cv=5,return_train_score=False)
clf.fit(digits.data,digits.target)
clf.cv_results_

{'mean_fit_time': array([0.0212038 , 0.11111994, 0.01375747, 0.11282272, 0.01398263,
        0.11168385, 0.01402764, 0.11121364]),
 'std_fit_time': array([0.00721131, 0.00262147, 0.00076647, 0.00198395, 0.00078138,
        0.0016993 , 0.00067141, 0.00122042]),
 'mean_score_time': array([0.00422282, 0.03601489, 0.00328407, 0.03527222, 0.00301509,
        0.03570175, 0.00326309, 0.03623285]),
 'std_score_time': array([0.00071428, 0.00056274, 0.00016749, 0.00016604, 0.00015896,
        0.00053226, 0.00011568, 0.00022925]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 50, 50],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 50, 'kernel': 'linear'},
  {'C': 50, 'kernel': 'rbf'}],
 'split0_test_score': array([0.96388889, 0.41111111, 0.96388889, 0.45277778, 0.96388889,
        0.45277778, 0.96388889, 0.45277778]),
 'split1_test_score': array([0.91944444, 0.45      , 0.91944444, 0.46944444, 0.91944444,
        0.46944444, 0.91944444, 0.46944444]),
 'split2_test_score': array([0.96657382, 0.454039  , 0.96657382, 0.47910864, 0.96657382,
        0.47910864, 0.96657382, 0.47910864]),
 'split3_test_score': array([0.9637883 , 0.44846797, 0.9637883 , 0.47910864, 0.9637883 ,
        0.47910864, 0.9637883 , 0.47910864]),
 'split4_test_score': array([0.92479109, 0.47910864, 0.92479109, 0.50139276, 0.92479109,
        0.50139276, 0.92479109, 0.50139276]),
 'mean_test_score': array([0.94769731, 0.44854534, 0.94769731, 0.47636645, 0.94769731,
        0.47636645, 0.94769731, 0.47636645]),
 'std_test_score': array([0.02097775, 0.02176115, 0.02097775, 0.01578414, 0.02097775,
        0.01578414, 0.02097775, 0.01578414]),
 'rank_test_score': array([1, 8, 1, 5, 1, 5, 1, 5], dtype=int32)}

In [76]:
df2 = pd.DataFrame(clf.cv_results_)
df2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.021204,0.007211,0.004223,0.000714,1,linear,"{'C': 1, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
1,0.111120,0.002621,0.036015,0.000563,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.411111,0.450000,0.454039,0.448468,0.479109,0.448545,0.021761,8
2,0.013757,0.000766,0.003284,0.000167,10,linear,"{'C': 10, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
3,0.112823,0.001984,0.035272,0.000166,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.452778,0.469444,0.479109,0.479109,0.501393,0.476366,0.015784,5
4,0.013983,0.000781,0.003015,0.000159,20,linear,"{'C': 20, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
5,0.111684,0.001699,0.035702,0.000532,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.452778,0.469444,0.479109,0.479109,0.501393,0.476366,0.015784,5
6,0.014028,0.000671,0.003263,0.000116,50,linear,"{'C': 50, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
7,0.111214,0.001220,0.036233,0.000229,50,rbf,"{'C': 50, 'kernel': 'rbf'}",0.452778,0.469444,0.479109,0.479109,0.501393,0.476366,0.015784,5

In [77]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [87]:
df2[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.947697
1        1          rbf         0.448545
2       10       linear         0.947697
3       10          rbf         0.476366
4       20       linear         0.947697
5       20          rbf         0.476366
6       50       linear         0.947697
7       50          rbf         0.476366

In [88]:
clf.best_score_

np.float64(0.9476973073351903)

In [89]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C' : [1,10,20,50],
    'kernel' : ['linear','rbf']
},cv=5,return_train_score=False,n_iter=3)
rs.fit(digits.data,digits.target)
rs.cv_results_
df3 = pd.DataFrame(rs.cv_results_)
df3[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0       20          rbf         0.476366
1       10          rbf         0.476366
2       10       linear         0.947697

In [90]:
rs.best_params_

{'kernel': 'linear', 'C': 10}

In [91]:
rs.best_score_

np.float64(0.9476973073351903)

## Different Models with different parameters

In [98]:
model_params = {
    'svm3' : {
        'model' : SVC(gamma='auto'),
        'params' : {
            'C' : [1,10,20,30],
            'kernel':['linear','rbf']
    }},
    'logistic_reg' : {
        'model' : LogisticRegression(),
        'params' : {
            'C' : [10,1,20,'auto']
        }
    },
    'Decision_tree' : {
        'model': DecisionTreeClassifier(),
        'params' : {
            'max_depth' : [5,10,20,30],
            'criterion' : ['gini','entropy']
        }
    },
    'Random_forest':{
        'model' : RandomForestClassifier(),
        'params' : {
            'max_depth' : [5,10,20,30]
        }
    },
    'Multinomial': {
        'model': MultinomialNB(),
        'params' : {}
    },
    'Gaussian': {
        'model': GaussianNB(),
        'params' : {}
    }
}

In [99]:
scores3 = []

for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(digits.data,digits.target)
    scores3.append({
        'model' : model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

df4 = pd.DataFrame(scores3 , columns=['model' , 'best_score', 'best_params'])
df4

d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
5 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'C' parameter of LogisticRegression must be a float in the range (0.0, inf]. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.91043175 0.91376509 0.91042866        nan]
  warnings.warn(
d:\Salik\Data Science\Machine Learning\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

           model  best_score                                best_params
0           svm3    0.947697               {'C': 1, 'kernel': 'linear'}
1   logistic_reg    0.913765                                   {'C': 1}
2  Decision_tree    0.814709  {'criterion': 'entropy', 'max_depth': 20}
3  Random_forest    0.941037                          {'max_depth': 30}
4    Multinomial    0.870350                                         {}
5       Gaussian    0.806928                                         {}